set(FASTDDS_STATISTICS=ON)
set(SQLITE3_SUPPORT ON)
set(THIRDPARTY ON)
set(THIRDPARTY_Asio FORCE)
set(THIRDPARTY_TinyXML2 FORCE)

set(BUILD_SHARED_LIBS OFF)
set(BUILD_DOCUMENTATION OFF)
set(COMPILE_EXAMPLES OFF)
set(COMPILE_TOOLS OFF)

set(CMAKE_CONFIGURATION_TYPES Release)

set(TYPE_LONG_DOUBLE 8)
