set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_SYSROOT iphonesimulator)
set(CMAKE_OSX_ARCHITECTURES x86_64;arm64)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
set(CMAKE_OSX_DEPLOYMENT_TARGET 12.0)

set(CMAKE_CXX_FLAGS "-Wno-shorten-64-to-32 -std=c++17")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
