unset(CMAKE_XCODE_ATTRIBUTE_INSTALL_PATH)

set(CMAKE_OSX_SYSROOT iphoneos)
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS macosx)
set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-iphonesimulator")
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTS_MACCATALYST YES)
set(CMAKE_OSX_ARCHITECTURES x86_64;arm64)
set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 13.1)
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.13)

set(CMAKE_CXX_FLAGS "-Wno-shorten-64-to-32 -std=c++17")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
