unset(CMAKE_XCODE_ATTRIBUTE_INSTALL_PATH)

set(CMAKE_OSX_SYSROOT iphoneos)
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS macosx)
set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-iphonesimulator")
set(CMAKE_XCODE_ATTRIBUTE_SUPPORTS_MACCATALYST YES)
set(CMAKE_OSX_ARCHITECTURES x84_64;arm64)
set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 13.1)
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.13)
